/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces.index'
import { Route as SpacesIdRouteImport } from './routes/spaces.$id'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiBookingsRouteImport } from './routes/api.bookings'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api.webhooks.razorpay'
import { Route as ApiWebhooksPayuRouteImport } from './routes/api.webhooks.payu'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api.webhooks.paystack'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiPaymentsCheckoutBookingIdRouteImport } from './routes/api.payments.checkout.$bookingId'
import { Route as ApiBookingsIdRejectRouteImport } from './routes/api.bookings.$id.reject'
import { Route as ApiBookingsIdCompleteRouteImport } from './routes/api.bookings.$id.complete'
import { Route as ApiBookingsIdCancelRouteImport } from './routes/api.bookings.$id.cancel'
import { Route as ApiBookingsIdAcceptRouteImport } from './routes/api.bookings.$id.accept'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIdRoute = SpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPayuRoute = ApiWebhooksPayuRouteImport.update({
  id: '/api/webhooks/payu',
  path: '/api/webhooks/payu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCheckoutBookingIdRoute =
  ApiPaymentsCheckoutBookingIdRouteImport.update({
    id: '/api/payments/checkout/$bookingId',
    path: '/api/payments/checkout/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookingsIdRejectRoute = ApiBookingsIdRejectRouteImport.update({
  id: '/$id/reject',
  path: '/$id/reject',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiBookingsIdCompleteRoute = ApiBookingsIdCompleteRouteImport.update({
  id: '/$id/complete',
  path: '/$id/complete',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiBookingsIdCancelRoute = ApiBookingsIdCancelRouteImport.update({
  id: '/$id/cancel',
  path: '/$id/cancel',
  getParentRoute: () => ApiBookingsRoute,
} as any)
const ApiBookingsIdAcceptRoute = ApiBookingsIdAcceptRouteImport.update({
  id: '/$id/accept',
  path: '/$id/accept',
  getParentRoute: () => ApiBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/spaces/$id': typeof SpacesIdRoute
  '/spaces/': typeof SpacesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/payu': typeof ApiWebhooksPayuRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/bookings/$id/accept': typeof ApiBookingsIdAcceptRoute
  '/api/bookings/$id/cancel': typeof ApiBookingsIdCancelRoute
  '/api/bookings/$id/complete': typeof ApiBookingsIdCompleteRoute
  '/api/bookings/$id/reject': typeof ApiBookingsIdRejectRoute
  '/api/payments/checkout/$bookingId': typeof ApiPaymentsCheckoutBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/spaces/$id': typeof SpacesIdRoute
  '/spaces': typeof SpacesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/payu': typeof ApiWebhooksPayuRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/bookings/$id/accept': typeof ApiBookingsIdAcceptRoute
  '/api/bookings/$id/cancel': typeof ApiBookingsIdCancelRoute
  '/api/bookings/$id/complete': typeof ApiBookingsIdCompleteRoute
  '/api/bookings/$id/reject': typeof ApiBookingsIdRejectRoute
  '/api/payments/checkout/$bookingId': typeof ApiPaymentsCheckoutBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/bookings': typeof ApiBookingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/spaces/$id': typeof SpacesIdRoute
  '/spaces/': typeof SpacesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/payu': typeof ApiWebhooksPayuRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/bookings/$id/accept': typeof ApiBookingsIdAcceptRoute
  '/api/bookings/$id/cancel': typeof ApiBookingsIdCancelRoute
  '/api/bookings/$id/complete': typeof ApiBookingsIdCompleteRoute
  '/api/bookings/$id/reject': typeof ApiBookingsIdRejectRoute
  '/api/payments/checkout/$bookingId': typeof ApiPaymentsCheckoutBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/owner'
    | '/register'
    | '/sitemap.xml'
    | '/api/bookings'
    | '/api/health'
    | '/spaces/$id'
    | '/spaces/'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/webhooks/paystack'
    | '/api/webhooks/payu'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/stripe'
    | '/api/bookings/$id/accept'
    | '/api/bookings/$id/cancel'
    | '/api/bookings/$id/complete'
    | '/api/bookings/$id/reject'
    | '/api/payments/checkout/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/owner'
    | '/register'
    | '/sitemap.xml'
    | '/api/bookings'
    | '/api/health'
    | '/spaces/$id'
    | '/spaces'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/webhooks/paystack'
    | '/api/webhooks/payu'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/stripe'
    | '/api/bookings/$id/accept'
    | '/api/bookings/$id/cancel'
    | '/api/bookings/$id/complete'
    | '/api/bookings/$id/reject'
    | '/api/payments/checkout/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/owner'
    | '/register'
    | '/sitemap.xml'
    | '/api/bookings'
    | '/api/health'
    | '/spaces/$id'
    | '/spaces/'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/auth/session'
    | '/api/webhooks/paystack'
    | '/api/webhooks/payu'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/stripe'
    | '/api/bookings/$id/accept'
    | '/api/bookings/$id/cancel'
    | '/api/bookings/$id/complete'
    | '/api/bookings/$id/reject'
    | '/api/payments/checkout/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBookingsRoute: typeof ApiBookingsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  SpacesIdRoute: typeof SpacesIdRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
  ApiWebhooksPayuRoute: typeof ApiWebhooksPayuRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiPaymentsCheckoutBookingIdRoute: typeof ApiPaymentsCheckoutBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$id': {
      id: '/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof SpacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/payu': {
      id: '/api/webhooks/payu'
      path: '/api/webhooks/payu'
      fullPath: '/api/webhooks/payu'
      preLoaderRoute: typeof ApiWebhooksPayuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/checkout/$bookingId': {
      id: '/api/payments/checkout/$bookingId'
      path: '/api/payments/checkout/$bookingId'
      fullPath: '/api/payments/checkout/$bookingId'
      preLoaderRoute: typeof ApiPaymentsCheckoutBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/$id/reject': {
      id: '/api/bookings/$id/reject'
      path: '/$id/reject'
      fullPath: '/api/bookings/$id/reject'
      preLoaderRoute: typeof ApiBookingsIdRejectRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/bookings/$id/complete': {
      id: '/api/bookings/$id/complete'
      path: '/$id/complete'
      fullPath: '/api/bookings/$id/complete'
      preLoaderRoute: typeof ApiBookingsIdCompleteRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/bookings/$id/cancel': {
      id: '/api/bookings/$id/cancel'
      path: '/$id/cancel'
      fullPath: '/api/bookings/$id/cancel'
      preLoaderRoute: typeof ApiBookingsIdCancelRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
    '/api/bookings/$id/accept': {
      id: '/api/bookings/$id/accept'
      path: '/$id/accept'
      fullPath: '/api/bookings/$id/accept'
      preLoaderRoute: typeof ApiBookingsIdAcceptRouteImport
      parentRoute: typeof ApiBookingsRoute
    }
  }
}

interface ApiBookingsRouteChildren {
  ApiBookingsIdAcceptRoute: typeof ApiBookingsIdAcceptRoute
  ApiBookingsIdCancelRoute: typeof ApiBookingsIdCancelRoute
  ApiBookingsIdCompleteRoute: typeof ApiBookingsIdCompleteRoute
  ApiBookingsIdRejectRoute: typeof ApiBookingsIdRejectRoute
}

const ApiBookingsRouteChildren: ApiBookingsRouteChildren = {
  ApiBookingsIdAcceptRoute: ApiBookingsIdAcceptRoute,
  ApiBookingsIdCancelRoute: ApiBookingsIdCancelRoute,
  ApiBookingsIdCompleteRoute: ApiBookingsIdCompleteRoute,
  ApiBookingsIdRejectRoute: ApiBookingsIdRejectRoute,
}

const ApiBookingsRouteWithChildren = ApiBookingsRoute._addFileChildren(
  ApiBookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBookingsRoute: ApiBookingsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  SpacesIdRoute: SpacesIdRoute,
  SpacesIndexRoute: SpacesIndexRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
  ApiWebhooksPayuRoute: ApiWebhooksPayuRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiPaymentsCheckoutBookingIdRoute: ApiPaymentsCheckoutBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
